[package]
name = "per-lob"
version = "0.1.0"
description = "Shadow Book — private limit order book on MagicBlock PER"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "per_lob"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "1.0.2"
ephemeral-rollups-sdk = { git = "https://github.com/magicblock-labs/ephemeral-rollups-sdk", branch = "main", features = ["anchor"] }
